### ISSUE TITLE
Importing Large VB6 Project "Succeeds" But Produces Broken .twinproj File

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#703]
**Describe the bug**
Importing a large VB6 project appears to succeed, but always produces a broken .twinproj file. Opening the project shows the following error:

![image](https://user-images.githubusercontent.com/5287585/152363373-46156993-6c7f-4cc9-9e0e-fad962490378.png)

If I open the .twinproj file in a text editor, some content is there but the file seems to be limited to a max of exactly 1MB - anything over that gets truncated. 

The log in the truncated project file shows "success" for every step of the import.

**To Reproduce**
1. Import a sufficiently large VB6 project.
2. twinBasic appears to be successful, and will let you save the imported project as a .twinproj file.
3. twinBasic will fail to open the file with a "WARNING: failed to deserialize file system. Some files might be lost or truncated." error.

**Expected behavior**
I would expect to be able to import large projects without getting a corrupt .twinproj file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.13.91

**Comment by jpbro** [comment]
Here's a large VB6 project you can test against: [https://github.com/tannerhelland/PhotoDemon](https://github.com/tannerhelland/PhotoDemon)

**Comment by WaynePhillipsEA** [comment]
Thanks.  I'll look at getting this fixed tomorrow.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in v0.14.8, thanks for reporting.    The PhotoDemon project now imports correctly (apart from the forms and controls of course).

**Comment by jpbro** [comment]
Hi Wayne, thanks for looking into this, I can confirm that PhotoDemon now imports properly and the process results in a valid & complete .twinproj file.

Unfortunately, I have a few other projects I've tried that are still failing to produce a valid file. They do get further along though - I don't get an error about them being truncated anymore, but when I try to open the sources folder I get a "spinning wheel of death" beside the Source folder that spins for a few minutes after which point this error eventually appears:

![image](https://user-images.githubusercontent.com/5287585/152852304-a78213e7-5e03-4db8-99de-040a3b19084e.png)

If I try to double-click one of the errors in the Problems window, it will sometimes take me to the error in the full source file, but sometimes I'll see the following error:

![image](https://user-images.githubusercontent.com/5287585/152853319-f3655661-818a-4592-ba67-f46881e62335.png)

Here's a hunch that I haven't had a chance to test further yet - it looks like all the missing file *might* be in parent folders, or in relative paths that take us up out of the main project .VBP folder. Could there be a problem with relative path resolution?

For example the above modLibStock.bas file has the following Module line in the VBP file"

`Module=modLibStock; ..\modLibStock.bas`

Unfortunately I can't publish links to the source since they are closed-source/proprietary to my company. Are there any logs are anything that I can provide that might give you a better idea as to what's going wrong?

**Comment by WaynePhillipsEA** [comment]
Yes it's quite possible those relative paths are preventing the import of those documents, so I'll check that tomorrow.

However, I suspect the compiler is crashing on something in side your project anyway.  If possible, edit the build configuration (win32/win64) and disable the compiler - it should be the last option in the build configuration settings.  But... It might be that you aren't able to get that far, so let me know if not and I'll give you further instruction.

If you manage to disable the compiler, you should be able to look around the source files without it crashing at least... and then we can go from there.

**Comment by jpbro** [comment]
I was able to disable to compiler and re-open, but I still get an spinning wheel beside the Sources folder when I try to expand it.

When I leave the compiler enabled, I can get into the sources folder & files by double-clicking any error in the Problem list. One thing I noticed is that there are a *lot* of errors (>1k), so perhaps that's part of the problem. One example that generates a lot of errors: I fully qualify things like PropertyBag as VBRUN.PropertyBag. If I strip the "VBRUN." part, then the error goes away. Perhaps tB should be translating fully qualified VBRUN objects to its own internal implements? In any case, I will strip those all out to see if there's any improvement.

**Comment by WaynePhillipsEA** [comment]
I don't think it's the number of issues.  For example the PhotoDemon project has 1700+ issues (mostly missing form problems), but navigates fine.

We haven't implemented PropertyBag yet, so that would be an expected problem.

**Comment by WaynePhillipsEA** [comment]
Would you be able to share the project privately?  Just trying to think of the easiest resolution... but it's fine if you can't.

**Comment by jpbro** [comment]
I don't have a problem sharing the source privately. but before I do I thought I would report this: I just tried removing the handful of files that were located at relative paths upwards from the VBP path, and the import succeeded and I could navigate all of the files in the Sources folder without issue, so think this is the likely cause of the problem.

If you still need my source after investigating that avenue, please let me know where to send it. Thanks! :)

**Comment by WaynePhillipsEA** [comment]
Great, sounds like it should be an easy fix then.  Let's get the relative path issue fixed tomorrow, and then see if anything else comes up after that.  Thanks.

**Comment by jpbro** [comment]
Sounds great to me, thanks a lot!

**Comment by WaynePhillipsEA** [comment]
The relative paths issue on import should now be fixed in v0.14.9.  Let me know how you get on with it.

**Comment by jpbro** [comment]
I can confirm that v0.14.9 fixes the problem with relative paths on import, and that has in turned fixed the problem with opening the Sources folder in VSC. Thank you!

One last thing before we close this issue- for all the unique errors that I'm seeing (that don't already have an Issue opened here of course), would you like me to open a new separate issue for each of them? Or will that be too much noise?

**Comment by WaynePhillipsEA** [comment]
> One last thing before we close this issue- for all the unique errors that I'm seeing (that don't already have an Issue opened here of course), would you like me to open a new separate issue for each of them? Or will that be too much noise?

Generally, I would prefer one issue per problem as it's easier for me to digest and better for tracking purposes, but if there's a couple of issues that are very closely related, then I'm fine with grouping them.

So I'll close this now as I think this issue is resolved.  Thanks!

**Comment by mika76** [comment]
@WaynePhillipsEA are relative paths working now - I'm hitting issues opening a .vbp project (on release 60 https://github.com/WaynePhillipsEA/twinbasic/releases/tag/beta-60) - in m vbp there are a lot of relative paths which go up to the parent and then into other folders.

eg
```
Class=clsEvents; ..\COMMON\clsEvents.cls
Form=frmSealNumber.frm
Class=clsUpdator; ..\COMMON\clsUpdator.cls
Class=clsMD5Hash; ..\COMMON\clsMD5Hash.cls
Class=clsSystemInfo; ..\COMMON\clsSystemInfo.cls
Module=modRRTools; ..\RemoteLogin\modRRTools.bas
```

Twinbasic is just stuck on the "Please wait" loading screen. Also are there any log files anywhere I can look at to see what the problem might be?
