### ISSUE TITLE
Windows Firewall

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#723]
**Describe the bug**
Not a real bug, something between a bug and a feature request. When I open the form editor, every time pops up this firewall message. I push the "Allow access" but next time, and practically every time, it comes back again and again. I have this issue only with the TWB.

**Expected behavior**
If I have already allowed it, I wouldnt like to see this message again.... :) 

**Screenshots**
See attached!
**Desktop (please complete the following information):**
 - OS: Windows7
 - twinBASIC compiler version 0.14.11
![Image344](https://user-images.githubusercontent.com/94013032/153265902-d092d32b-2f40-43a9-8c95-74a699d061ed.jpg)

**Comment by WaynePhillipsEA** [comment]
I suspect this is happening because Defender sees the compiler EXE has changed, and so _forgets_ the setting.  Since the compiler gets updated virtually daily, that might be the reason you're seeing this so often.

**Comment by uwbwsvd** [comment]
> e compiler EXE has changed

I have issues with PANDA 360. Every new version is detected. And is last 2- 3 hours (less or more) that the exe is given free.

**Comment by bclothier** [comment]
Would splitting the compiler into an EXE + a DLL avoid this issue? If the EXE simply acts as the "server" and call the actual implementation in DLL, DLL can keep changing but without tripping the firewall alert? Of course if there's a change in the communication between VSC and EXE, then that's unavoidable but if most of the changes are done with the implementation rather than the IPC, that might allevaite the problem?

**Comment by WaynePhillipsEA** [comment]
I've just pushed out v0.14.12 where I've tweaked the setup for the websocket that is used between the Form Designer and the compiler, with the aim of not triggering Windows Defender Firewall.  I'm not 100% convinced it will work... but we'll see.

It should be available to you in about 5 minutes.

**Comment by WaynePhillipsEA** [comment]
> Would splitting the compiler into an EXE + a DLL avoid this issue? If the EXE simply acts as the "server" and call the actual implementation in DLL, DLL can keep changing but without tripping the firewall alert? Of course if there's a change in the communication between VSC and EXE, then that's unavoidable but if most of the changes are done with the implementation rather than the IPC, that might allevaite the problem?

No I don't think that would help, as defender is triggered by the host EXE process (not the DLL where the code might reside).

**Comment by WaynePhillipsEA** [comment]
> > e compiler EXE has changed
> 
> I have issues with PANDA 360. Every new version is detected. And is last 2- 3 hours (less or more) that the exe is given free.

There's not much I can do about that, as the EXE that gets updated virtually every day... sometimes several times per day.   You can of course turn off auto-updates for extensions in VS Code, and then update them manually after they've been in the wild for some time, which might help.

**Comment by DinyaZ** [comment]
I have tried now with the latest .12 version, but the issue remained unchanged.....!

**Comment by bclothier** [comment]
I suspect that you'd need to wait for additional updates to see if the changes in the .12 had any effect since the updating to .12 would still trip the firewall change because it doesn't have that change made to the socket settings.

Or are you saying you see the firewall dialog multiple times with .12?

**Comment by DinyaZ** [comment]
No, came up only the first time after the update! So ok, let us see how it vill work with the next update! :)

**Comment by WaynePhillipsEA** [comment]
Ah no, if anything, I was hoping the change would've meant that we didn't trigger the Defender at all, so unfortunately that failed.

**Comment by WaynePhillipsEA** [comment]
Argh.... I've spotted the problem.  Will be fixed in the next update

**Comment by WaynePhillipsEA** [comment]
So I'm hopeful the Defender Firewall won't be triggered now as of v0.14.13 :)

I've also now split the compiler into an EXE loader+DLL configuration so that the EXE loader should eventually become more trusted and perhaps become less prone to false-positive anti-virus prompts.  Note that the EXE simply loads the DLL though, so it wont fool the more intrusive anti-virus scans.

This split into a DLL also opens the door for an external compiler API...

**Comment by WaynePhillipsEA** [comment]
@DinyaZ are you still getting prompted by the Firewall since v0.14.13?

**Comment by DinyaZ** [comment]
If it helps, you can connect to my machine to check it, if you have Anydesk!

**Comment by DinyaZ** [comment]
The firewall message itself is solved, it doesnt come again

**Comment by WaynePhillipsEA** [comment]
> Weird error messages comes.

Please open a new issue with details of the error message(s).  Thanks.

**Comment by Kr00l** [comment]
On a private computer I saw this firewall message as well. Now I updated it to the latest tB version and it doesn't appear.

Will re-check also on that one on the next release to be sure.

**Comment by DinyaZ** [comment]
> No firewall message on 0.14.16. So I think it's solved. Let's keep it open a while so DinyaZ can confirm also.

The issue with firewall message itself iseems to be solved!

**Comment by uwbwsvd** [comment]
> > e compiler EXE has changed
> 
> I have issues with PANDA 360. Every new version is detected. And is last 2- 3 hours (less or more) that the exe is given free.

Seems to have disappeared with the changes that were made.
