### ISSUE TITLE
the right position of the controls is not maintained.

### ISSUE THREAD

**Issue by camomille22003** [WaynePhillipsEA/twinbasic#949]
With all the "Left Properties" of the "MSFlexgrid" set to zero, impossible to keep them on the left, they gradually move to the right

[essai.zip](https://github.com/WaynePhillipsEA/twinbasic/files/9000750/essai.zip)

![Animation14](https://user-images.githubusercontent.com/33807881/176172984-55123733-515e-4dc6-8f7d-0caba7485033.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 63

**Comment by wqweto** [comment]
I'm so glad I stopped using `SSTab` abomination of a container control like 20 years ago.

JFYI, with `SSTab` you can focus controls on inactive tabs using TAB key. This is not a TB bug but a `SSTab` bug (reproducible in VB6) a complete show-stopper for any retail software.

You have to place all controls on a tab in a separate container (like a `PictureBox` or a `Frame`) and show/hide these containers on `TabClick` event respectively.

But if you eventually resort to this "re-parenting" then you are a good to leave the 90-ies and go straight for the `TabStrip` control with modern visual styles etc.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 64.  Thanks.

**Comment by wqweto** [comment]
> It works perfectly in VB6 without Frame or PictureBox.

Checkout this [Form1.zip](https://github.com/WaynePhillipsEA/twinbasic/files/9002256/Form1.zip)
```
Option Explicit

Private Sub MSFlexGrid1_GotFocus()
    Caption = "MSFlexGrid1_GotFocus"
End Sub

Private Sub MSFlexGrid2_GotFocus()
    Caption = "MSFlexGrid2_GotFocus"
End Sub

Private Sub MSFlexGrid3_GotFocus()
    Caption = "MSFlexGrid3_GotFocus"
End Sub

Private Sub SSTab1_GotFocus()
    Caption = "SSTab1_GotFocus"
End Sub
```
Press TAB key and observe form's Caption cycling the grids i.e. you can focus controls on invisible tabs.

Do you find this behavior acceptable?

**Comment by EduardoVB** [comment]
Worth to mention that there is another potential issue with the SSTab, that is it won't work with very high DPI (above 300% IIRC).
That's why in my approach the shift to the left of the controls in non visible tabs is not fixed on -75000 anymore, but dynamically applied according to the DPI.
With -75000 twips the values hit a [hard Windows limit](https://www.vbforums.com/showthread.php?888201-RESOLVED-Weird-issue-with-controls-position-at-high-DPI).

BTW I think I've read that the TabStrip in .NET is a control container. IDK how it hides the controls of non-active tabs.

**Comment by bclothier** [comment]
Forgive me if I'm asking a silly question -- but why all the shifting around of the control? Wouldn't it be far simpler to change the style `WS_VISIBLE`, perhaps via `SetWindowPos` API?

**Comment by EduardoVB** [comment]
> stacked on top of each other.

That's a terrible mess (for my taste).



> You might try to use a "buddy" control setting to assign companion `picTab` control-array mentioned above

🤦‍♂️

**Comment by EduardoVB** [comment]
My control actually is very much the same as is the TabStrip in VB.NET now (since it is themed and is a control container), BTW. 
Just keeping the interface of the SStab.

IDK why all this rant.
